[[dsl-examples]]
= DSL Examples
This section contains documentation and instructions for various
samples we provide with a distribution. Below sub-sections are
mostly organised around different languages and how those
languages are organised to a services provided by a SDSL.

== Simple Language
_Simple Language_ is a language demonstrating very simplistic way
to get you familiar with language features without introducing too
much overhead with additional supported features.

=== Process Server
_Process Server_ is used for a _LSP Clients_ using normal _STDIO_.

=== Socket Server
_Socker Server_ is used for a _LSP Clients_ using normal socker
connections.

=== UI Editor
_UI Editor_ is and example using websockets for a transport.

== Wordcheck Language
_Wordcheck Language_ is a language recognizing words from a given
text and checking those words against legal allowed words.

[source,java,indent=0]
----
include::samples/demo/wordcheckdsl/EnableWordcheckLanguage.java[tags=snippet1]
----

[source,java,indent=0]
----
include::samples/demo/wordcheckdsl/WordcheckLanguageLinter.java[tags=snippet1]
----

[source,java,indent=0]
----
include::samples/demo/wordcheckdsl/WordcheckLanguageCompletioner.java[tags=snippet1]
----

=== UI Editor
_UI Editor_ is and example using websockets for a transport.

[source,java,indent=0]
----
include::samples/demo/wordcheckdsleditor/Application.java[tags=snippet1]
----

[NOTE]
====
`SampleRedirectConfiguration` simply defines a bean to redirect request from
root path to `index.html` as _Spring Boot_ doesn't do this automatically for
_WebFlux_ as it does for _Servlet_ environment.
====

[source,yaml,indent=0]
----
include::samples/wordcheckdsleditor/src/main/resources/application.yml[tags=snippet1]
----

